### ISSUE TITLE
Addon don't show as Available

### ISSUE THREAD

**Issue by tamalsaha** [kluster-manager/cluster-auth-manager#6]
- https://open-cluster-management.io/developer-guides/addon/#monitor-addon-healthiness

```
status:
  conditions:
  - lastTransitionTime: "2024-03-26T20:59:56Z"
    message: install completed with no errors.
    reason: InstallSucceed
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-03-26T20:59:55Z"
    message: Registration of the addon agent is configured
    reason: NilRegistration
    status: "True"
    type: RegistrationApplied
  - lastTransitionTime: "2024-03-26T20:59:56Z"
    message: manifests of addon are applied successfully
    reason: AddonManifestApplied
    status: "True"
    type: ManifestApplied
  - lastTransitionTime: "2024-03-26T20:59:57Z"
    message: The status of cluster-auth add-on is unknown.
    reason: ManagedClusterAddOnLeaseNotFound
    status: Unknown
    type: Available
```
